name: black
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-black@v1